version: "3.9"

services:
  backend:
    build: .
    container_name: student_feedback_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - JWT_SECRET_KEY=supersecretkey
      - MONGO_URI=mongodb://mongo:27017/student_feedback
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: student_feedback_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
